version: 3

dotenv:
  - .env

tasks:
  pg:
    deps: [pg-front, dev-server]
  # DOUBLE CHECK $PLAYGROUND_PATH BEFORE RUNNING
  pg-front:
    cmds:
      - cd $PLAYGROUND_PATH&&pwd&&npm run dev
  dev-server:
    cmds:
      - cargo watch -x run
    dir: crates/blve_dev_server
  build:
    cmds:
      - |
        cd ./crates/blve_compiler/ && wasm-pack build --target nodejs
        cp ./crates/blve_compiler/pkg/*.js ./npm-pkg/src/wasm-compiler/
        cp ./crates/blve_compiler/pkg/*.ts ./npm-pkg/src/wasm-compiler/
        cp ./crates/blve_compiler/pkg/*.wasm ./npm-pkg/src/wasm-compiler/
        cd ./npm-pkg/src/wasm-compiler && npm run build
        mkdir -p ./npm-pkg/dist/wasm-compiler
        cp -r ./npm-pkg/src/wasm-compiler/* ./npm-pkg/dist/wasm-compiler/
  build-web:
    cmds:
      - cd ./crates/blve_compiler/ && wasm-pack build --target web
