[package]
name = "blve_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html_parser = "0.6.3"
nom = "7.1.3"
rome_js_parser = "0.0.2"
rome_js_syntax = "0.0.2"
