[workspace]
# Use the newer version of the cargo resolver
# https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
resolver = "2"
members = [
  "lunas_generator",
  "blve_parser",
  "lunas_compiler",
  "blve_html_parser",
  "lunas_dev_server",
]
