[package]
name = "blve_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blve_parser = { version = "0.1.0", path = "../blve_parser" }
serde_json = "1.0.96"
html_parser = { git = "https://github.com/s19514tt/rust-html-parser-fork-for-blve/", rev = "c3beb6e38aa70ec5694357d6bd4241987bbc9cd3" }
nanoid = "0.4.0"
