name: Check package.json version

on:
  pull_request:
    branches:
      - beta

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check package.json version format
        run: |
          VERSION=$(cat ./npm-pkg/package.json | jq -r '.version')
          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-beta\.[0-9]+$ ]]; then
            echo "Version format is correct"
          else
            echo "Version format is incorrect" && exit 1
          fi
          export VERSION

      - name: Create PR review
        if: ${{ failure() }}
        run: gh pr comment ${{ github.event.pull_request.number }} --body "The version in package.json '$VERSION' does not adhere to the specified format ([digit].[digit].[digit]-beta.[digit]). Please correct it."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
