name: Publish npm package

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Check package.json version format
        run: |
          make build
          cd npm-pkg && npm publish --tag beta
