name: Publish npm package

on:
  pull_request:
    branches:
      - beta
    types: [closed]
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build
        run: |
          make build
      - name: Publish rust crate
        run: |
          npm ci
          npm publish --tag beta
        working-directory: ./npm-pkg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
